# Generated by Django 5.2.1 on 2025-06-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cross',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=50, primary_key=True, serialize=False)),
                ('mf', models.CharField(choices=[('M', 'M'), ('F', 'F')], db_column='M/F', max_length=1)),
                ('hand', models.CharField(choices=[('R', 'R'), ('L', 'L')], db_column='Hand', max_length=1)),
                ('age', models.IntegerField(db_column='Age')),
                ('educ', models.FloatField(blank=True, db_column='Educ', null=True)),
                ('ses', models.FloatField(blank=True, db_column='SES', null=True)),
                ('mmse', models.FloatField(blank=True, db_column='MMSE', null=True)),
                ('cdr', models.FloatField(blank=True, db_column='CDR', null=True)),
                ('etiv', models.IntegerField(db_column='eTIV')),
                ('nwbv', models.FloatField(db_column='nWBV')),
                ('asf', models.FloatField(db_column='ASF')),
                ('delay', models.FloatField(blank=True, db_column='Delay', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Long',
            fields=[
                ('subject_id', models.CharField(db_column='Subject ID', max_length=50, primary_key=True, serialize=False)),
                ('mri_id', models.CharField(db_column='MRI ID', db_index=True, max_length=50)),
                ('group', models.CharField(choices=[('Nondemented', 'Nondemented'), ('Demented', 'Demented'), ('Converted', 'Converted')], db_column='Group', max_length=50)),
                ('visit', models.IntegerField(db_column='Visit')),
                ('mr_delay', models.IntegerField(db_column='MR Delay')),
                ('mf', models.CharField(choices=[('M', 'M'), ('F', 'F')], db_column='M/F', max_length=1)),
                ('hand', models.CharField(choices=[('R', 'R'), ('L', 'L')], db_column='Hand', max_length=1)),
                ('age', models.IntegerField(db_column='Age')),
                ('educ', models.IntegerField(db_column='EDUC')),
                ('ses', models.FloatField(blank=True, db_column='SES', null=True)),
                ('mmse', models.FloatField(db_column='MMSE')),
                ('cdr', models.FloatField(db_column='CDR')),
                ('etiv', models.IntegerField(db_column='eTIV')),
                ('nwbv', models.FloatField(db_column='nWBV')),
                ('asf', models.FloatField(db_column='ASF')),
            ],
        ),
    ]
