# data:
#   base_path: "data"
#   cross_file: "cross.csv"
#   long_file: "long.csv"

features:
  # drop_columns: ['group', 'id', 'delay', 'subject_id', 'mri_id', 'visit', 'mr_delay']
  # scale: ['age', 'educ', 'ses', 'mmse', 'cdr', 'etiv','nwbv', 'asf']
  # ohe: ['mf', 'hand']
  # label: "group"
  drop_columns: ['Group', 'ID', 'Delay', 'Subject ID', 'MRI ID', 'Visit', 'MR Delay']
  scale: ['Age', 'EDUC', 'SES', 'MMSE', 'CDR', 'eTIV','nWBV', 'ASF']
  ohe: ['M/F', 'Hand']
  label: "Group"

classifier:
  xgboost:
    random_state: 42
    n_jobs: -1

split:
  test_size: 0.2
  random_state: 42